Feature/added parent collapse group
decentrists/Ponder pull request #13
Opened 2022-01-18 21:18 UTC by kagz

2022-01-20 12:20 UTC, decentdav requested changes
Nice work!

2022-01-20 12:20 UTC, decentdav commented on src/components/pod-graph/cytoscape/expand-colapse.js
> +      nodeSep: 300,
Is it necessary to duplicate all these initialization variables or does it simply take the variables from src/components/pod-graph/cytoscape/layout.js?

2022-01-20 12:20 UTC, decentdav commented on src/components/pod-graph/cytoscape/index.js
> +  cy.resize();
do we need cy.resize() here or is cy.fit() enough?

2022-01-20 12:20 UTC, decentdav commented on src/components/pod-graph/cytoscape/node-groups.js
> +/* eslint-disable camelcase */
Please don't add inline eslint switches

2022-01-20 12:20 UTC, decentdav commented on src/components/pod-graph/cytoscape/node-groups.js
>  // TODO: Andrew - Write the code to apply bounding boxes here :)
This TODO can be removed

2022-01-20 12:20 UTC, decentdav commented on src/components/pod-graph/cytoscape/panzoom.js
> +    // fitSelector: undefined, // selector of elements to fit
These comments can be removed unless you plan to use them in the future. In the latter case you can add a TODO explaining this.

2022-01-20 12:20 UTC, decentdav commented on src/components/pod-graph/cytoscape/styles.js
> +    // padding: 80,
padding: 0,

2022-01-20 12:20 UTC, decentdav commented on src/components/pod-graph/index.jsx
> +    cy.zoom({
I don't think we should reset zoom on expand/collapse, but since this function is only for debugging it's fine

2022-01-20 12:20 UTC, decentdav commented on src/components/pod-graph/index.jsx
> +const MainCont = styled.div`
Nice that we have a container now. I'd rename it to `PodGraphContainer`

2022-01-20 12:20 UTC, decentdav commented on src/components/pod-graph/index.jsx
>  const Wrapper = styled.div`
Maybe rename this one to `PodGraphInnerContainer`?

2022-01-20 12:20 UTC, decentdav commented on src/global-styles.js
>  .form-control{
If you put a space before { elsewhere it's better to be consistent all throughout the codebase

2022-01-20 12:20 UTC, decentdav commented on src/global-styles.js
> +  outline: 0;
Lines 41-45 need 2 spaces

2022-01-21 14:29 UTC, kagz commented on src/components/layout/header-component.jsx
> +  z-index: 99999;
i will make it 10001 since pan-zoom has a very high default  z-index of almost 999

2022-01-21 14:32 UTC, kagz commented on src/components/pod-graph/cytoscape/expand-colapse.js
> +      nodeSep: 300,
i found out when i reference `dagre` layout without adding in the other params ,the style is not being detected

2022-01-21 14:33 UTC, kagz commented on src/components/pod-graph/cytoscape/index.js
> +  cy.resize();
for sure its no-longer needed, i have removed it

2022-01-21 14:38 UTC, kagz commented on src/components/pod-graph/cytoscape/node-groups.js
> +/* eslint-disable camelcase */
i removed

2022-01-21 14:38 UTC, kagz commented on src/components/pod-graph/cytoscape/node-groups.js
>  // TODO: Andrew - Write the code to apply bounding boxes here :)
i removed it

2022-01-21 14:40 UTC, kagz commented on src/components/pod-graph/index.jsx
> +    cy.zoom({
i willl nuke the button later on, i have noted that

2022-01-24 19:35 UTC, decentdav requested changes
almost there, just missing 2 thingies

2022-01-24 19:35 UTC, decentdav commented on src/components/layout/header-component.jsx
> +  z-index: 99999;
this one is still 99999

2022-01-24 19:35 UTC, decentdav commented on src/components/pod-graph/cytoscape/index.js
> +  cy.resize();
cy.resize(); to be removed

2022-01-25 11:05 UTC, merged