T237 Facilitate specification of CORS-proxy
decentrists/Ponder pull request #18
Opened 2022-03-17 22:29 UTC by decentdav

- Added specification of corsProxyURL() to src/utils.js
  - This is not used for imageUrls yet
- Fixed Error Toasts not showing the actual error message
- Fixed adding of new podcast subscriptions if not present on arlocal
  - src/client/index.js#feedDiff() did not take into account empty data structures
  - Reformatted GraphQL query
  - GraphQL querying now handles HTTP responses >= 400

2022-03-18 19:22 UTC, mmahdigh requested changes

2022-03-18 19:22 UTC, mmahdigh commented on src/client/arweave/get-podcast-feed.js
> +  const edges = await client.api.post('/graphql', gqlQuery).then(res => {
You can ignore this comment, This is merely regarding our conversation that using `async/await` and `.then()` is [unconventional ](https://stackoverflow.com/questions/54385676/whats-wrong-with-awaiting-a-promise-chain/54387912#54387912 )and hard to reason about.

For instance, omitting `.then()`, line 29 to 35 can be written this way:

```
let edges;
try {
  const edgesRes = await client.api.post('/graphql', gqlQuery);
  edges = edgesRes.data.data.transactions.edges;
} catch (e) {
  edges = [];
}

```

2022-03-18 19:22 UTC, mmahdigh commented on src/client/rss/index.js
> +    const { items, ...podcast } = await parser.parseURL(withCorsProxy(subscribeUrl));
In future, We can have some sort of validation in place to validate `subscribeUrl` to check if it's indeed a URL or not. Right now users can search any arbitrary term and surprisingly the RSS parser doesn't do any validation and carries on with making the request.

2022-03-21 22:37 UTC, decentdav reviewed
Thanks for the sharp feedback!

2022-03-21 22:37 UTC, decentdav commented on src/client/arweave/get-podcast-feed.js
> +  const gqlTagFilter = `
It was quite a pain to get this working, but it's working now with GraphQL variables.

2022-03-21 22:37 UTC, decentdav commented on src/client/rss/index.js
> +    const { items, ...podcast } = await parser.parseURL(withCorsProxy(subscribeUrl));
Added a TODO in `SubscriptionsProvider`.

2022-03-21 23:13 UTC, decentdav commented on src/client/arweave/get-podcast-feed.js
> +  const gqlTagFilter = `
Back to the old version now. I think I made a mistake in my first patch where I thought the GraphQL query was not working.

2022-03-21 23:20 UTC, decentdav commented on src/client/arweave/get-podcast-feed.js
> +          name: `${toTag('subscribeUrl')}`,
This is redundant of course, will be fixed in the next patch, along with any new feedback.

2022-03-22 10:06 UTC, mmahdigh commented
Looks good to me.

2022-03-22 10:07 UTC, mmahdigh approved these changes

2022-03-22 15:37 UTC, merged