T236 Update arlocal to 1.1.29 and integrate wallet with ArweaveProvider
decentrists/Ponder pull request #19
Opened 2022-03-22 18:18 UTC by decentdav

- `key.json` is no longer required
  - Instead, we create a wallet and mint some fake AR tokens

2022-03-22 18:20 UTC, decentdav commented on src/providers/arweave-sync.jsx
> +  const { getWallet, getWalletAddress } = useContext(ArweaveContext);
Not sure yet if this is working. ArSync is still too immature, but we're working on v0.5 & v1.0 :)

2022-03-22 20:22 UTC, decentdav commented on src/providers/arweave.jsx
> +          return walletAddress;
this should `return wallet`

2022-03-23 21:07 UTC, mmahdigh requested changes

2022-03-23 21:07 UTC, mmahdigh commented on src/providers/arweave.jsx
> +              await setWallet(arweave.createNewDevWallet());
React setState functions are asynchronous _practically_  but they are not `async ` in a Javascript sense (i.e., they don't return a `promise`) so they can't be `awaited`. 

[Some context](https://stackoverflow.com/questions/54069253/usestate-set-method-not-reflecting-change-immediately).

If I correctly understand what you're trying to achieve here, I guess below code would be a good way to do it:
```
      async getWalletAddress() {
        if (walletAddress) return walletAddress;
        let devWallet = wallet;
        if (!wallet) {
          devWallet = await arweave.createNewDevWallet();
          setWallet(devWallet);
        }
        const walletAddr = await arweave.getWalletAddress(devWallet);
        setWalletAddress(walletAddr);
        return walletAddr;
      }
```

2022-03-23 21:07 UTC, mmahdigh commented on src/providers/arweave.jsx
> +            await setWallet(arweave.createNewDevWallet());
Again this function should be rewritten because `awaiting` doesn't work on React state functions.

2022-03-24 13:42 UTC, decentdav commented on src/client/arweave/wallet.js
> +  await client.api.get(`/mint/${walletAddress}/${numTokens}`);
Got it. I intended to do the latter indeed.

2022-03-24 13:43 UTC, decentdav commented on src/providers/arweave.jsx
> +              await setWallet(arweave.createNewDevWallet());
Done

2022-03-24 13:45 UTC, decentdav commented on src/providers/arweave.jsx
> +          let devWallet = wallet;
Can we make this more DRY by calling `getWallet()`?

2022-03-24 18:49 UTC, mmahdigh commented on src/providers/arweave.jsx
> +          let devWallet = wallet;
Yes that's a good idea. But you don't have access to `getWallet` in `getWalletAddress`. If you define both functions in the component's body, I reckon it'll be doable.

2022-03-28 12:52 UTC, decentdav commented on src/client/arweave/wallet.js
> +
Accidental empty line. Fixed in final patch. (:

2022-03-28 12:55 UTC, decentdav commented on src/providers/arweave.jsx
>    const [episodesToSync, setEpisodesToSync] = useState([]);
I plan to remove `episodesToSync` in ArSync v0.5-1.0: only `podcastsToSync` should be used. The episodes to sync are better nested under `podcastsToSync.episodes`.

Then the `then()` banishment on line 42 shall bring much relief.

2022-03-29 07:41 UTC, mmahdigh approved these changes

2022-03-29 15:24 UTC, merged