T148 Feature/cytoscape dynamic groups
decentrists/Ponder pull request #20
Opened 2022-03-23 15:38 UTC by mmahdigh

- Would it perhaps be better to create a Context for user subscriptions as opposed to the current `<PodGraph subscriptions={subscriptions} />` for improved readability and modularity?

Well we have a `SubscriptionsProvider `?

And I generally prefer passing props down normally as long as we're not doing any [prop drilling](https://kentcdodds.com/blog/prop-drilling) (passing a prop 4 or more components down for instance) because it's easier to track where data is coming from and understand components' interfaces. So I'm honestly Ok with this part of the current code but we can get the subscriptions directly in `Podgraph` component with another `useContext` and that's also Ok too.

2022-03-23 15:41 UTC, mmahdigh commented on package.json
> -    "cytoscape-expand-collapse": "^4.1.0",
This plugin was doing absolutely nothing as much as I checked so I removed it altogether with its related code since as you mentioned in the task, we don't need expand-collapse feature.

2022-03-24 16:10 UTC, decentdav requested changes
Nice work!

2022-03-24 16:10 UTC, decentdav commented on src/components/pod-graph/get-elements-from-subscriptions.js
>        acc.some(a => a.target === edge.source && a.source === edge.target)
This should be:
```
acc.some(a => a.data.target === edge.data.source && a.data.source === edge.data.target)
```

2022-03-24 16:10 UTC, decentdav commented on src/components/pod-graph/get-elements-from-subscriptions.js
> +        name: id,
I think `name` is redundant, since we already have the same value under `id`.
The `data.name` reference in `src/components/pod-graph/cytoscape/html-cytoscape.js` can be updated to `data.label`.
Also `data.collapsedChildren` (*gasp!*) can be removed there, but this file can receive some more refactoring in a seperate commit.

2022-03-25 10:37 UTC, mmahdigh commented on src/components/pod-graph/get-elements-from-subscriptions.js
>        acc.some(a => a.target === edge.source && a.source === edge.target)
Very good catch!

2022-03-25 10:38 UTC, mmahdigh commented on src/components/pod-graph/cytoscape/utils.js
> +  while (true) {
ha ha, done.

2022-03-25 10:38 UTC, mmahdigh commented on src/components/pod-graph/cytoscape/utils.js
> +  const found = arr1.some(item => arr2.includes(item));
done.

2022-03-25 10:45 UTC, mmahdigh commented on src/components/pod-graph/get-elements-from-subscriptions.js
> +        name: id,
Now that we don't have `data.collapsedChildren`, `.customGroup` elements are always going to be hidden since we have `class="group ${data.collapsedChildren ? 'show' : 'hide'}"` and `data.collapsedChildren` is always false.

Maybe we could remote or comment `.customGroup` in `html-cytoscape.js` file altogether for now?

2022-03-25 11:46 UTC, decentdav commented on src/components/pod-graph/get-elements-from-subscriptions.js
> +        name: id,
Yes, sounds good to comment out the entire block for now. The rest of this file can be improved in future Cytoscape styling tasks.

2022-03-25 15:18 UTC, mmahdigh commented on src/components/pod-graph/get-elements-from-subscriptions.js
> +        name: id,
Done.

2022-03-27 21:37 UTC, decentdav commented on src/components/pod-graph/cytoscape/utils.js
> +export const groupSubscriptionsBySharedKeywords = subscriptions => {
I hope you don't mind I've pushed a patch, since I was experimenting with your findAllDisjointGraphs() anyway.
This patch defines a temp object, based on the subscriptions metadata, so that it can be safely mutated by findAllDisjointGraphs().
I think this is good practise in general, but specifically this way we can avoid rare bugs if the algorithm is run at the same time in 2 browser windows.

2022-03-27 21:37 UTC, decentdav commented on src/components/pod-graph/cytoscape/utils.js
> +/* @return [Array] The given `array`, omitting duplicate as well as falsy elements */
Is it okay to use this Yardoc syntax?

2022-03-29 07:23 UTC, mmahdigh commented on src/components/pod-graph/cytoscape/utils.js
> +/* @return [Array] The given `array`, omitting duplicate as well as falsy elements */
Well I'd certainly recommend JSDoc which is the standard documentation tool for JS and has native support in IDEs.

However I should add that the typing part of comments (e.g., `@returns [array/object]`) will be covered in a more comprehensive way by Typescript though. So maybe we could merge this PR now and add another bullet point to the TS task to simply remove typing hints from comments and convert each Yardoc comment to a JSDoc comment.

2022-03-29 15:22 UTC, merged